config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :users
  resources :skills
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_one :skill
  has_many :skill_users
  has_many :users, through: :skill_users
  validates :skill_id, numericality: {only_integer: true, allow_nil: true}
end

app/models/skill_user.rb
class SkillUser < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :skill_users
    has_many :skills, through: :skill_users
    validates :points, numericality: { only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def index
        @skills = Skill.all 
        @score = Skill.connection.select_all("
with recursive skills_score(id,name,points,users) as (
    select s.id, s.name, u.points, u.id from skills s, users u, skill_users su
    where s.skill_id is null and u.id = su.user_id and s.id = su.skill_id
    union 
    select skills_score.id, skills_score.name, u2.points, u2.id from skills s2, users u2, skill_users su2, skills_score
    where s2.skill_id = skills_score.id and u2.id = su2.user_id and s2.id = su2.skill_id
) select id,name,sum(points) as points,count(users) as users_count from skills_score group by id,name order by id") 
    end

    def show
        @skill = Skill.find(params[:id])
    end

    def new
        @skill = Skill.new
    end

    def create
        @skill = Skill.new(skill_params)
        if @skill.save
            redirect_to @skill
        else
            render 'new'
        end
    end

    def score_query
    end


    private
        def skill_params
            params.require(:skill).permit(:name,:skill_id)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private
        def user_params
            params.require(:user).permit(:points)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgorizeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/index.html.erb
<h1>Listing skills</h1>
<%= link_to 'New skill', new_skill_path %>
<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Parent id</th>
        <th></th>
    </tr>

    <% @skills.each do |skill| %>
        <tr>
            <td><%= skill.id %></td>
            <td><%= skill.name %></td>
            <td><%= skill.skill_id %></td>
            <td><%= link_to 'Show', skill_path(skill) %></td>
        </tr>
    <% end %>
</table>
<h1>Score board</h1>
<% @score.each do |line| %>
    |<%= line["id"] %> | <%= line["name"] %> | <%= line["points"] %> | <%= line["users_count"] %> |<br> 
<% end %>

app/views/skills/new.html.erb
<%= form_with scope: :skill, url: skills_path, local: true do |form| %>
    <% if @skill.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@skill.errors.count, "error") %> prevented
                this skill from being saved:
            </h2>
            <ul>
                <% @skill.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    </p>

    <p>
    <%= form.label :parent %><br>
    <%= form.text_field :skill_id %>
    </p>

    <p>
    <%= form.submit %>
    </p>
<% end %>

app/views/skills/show.html.erb
<p>
<strong>Skill id</strong>
<%= @skill.id %>
</p>
<p>
<strong>Skill name</strong>
<%= @skill.name %>
</p>
<p>
<strong>Skill parent </strong>
<%= @skill.skill_id %>
</p>
<p>
<strong> Users scores </strong>
<% @skill.users.each do |user|%>
    <br>ID:<%= user.id %> - Points:<%= user.points %></br>
<% end %>
</p>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= link_to 'New user', new_user_path %>
<table>
    <tr>
        <th>Id</th>
        <th>Points</th>
        <th></th>
    </tr>

    <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.points %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
    <% end %>
</table>

app/views/users/new.html.erb
<%= form_with scope: :user, url: users_path, local: true do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@user.errors.count, "error") %> prevented
                this user from being saved:
            </h2>
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
    <%= form.label :points %><br>
    <%= form.text_field :points %>
    </p>

    <p>
    <%= form.submit %>
    </p>
<% end %>

app/views/users/show.html.erb
<p>
<strong>User id</strong>
<%= @user.id %>
</p>
<p>
<strong>User points</strong>
<%= @user.points %>
</p>

app/views/welcome/index.html.erb
<h1>Agorize test app</h1>
<%= link_to 'User listing', controller: 'users' %>
<%= link_to 'Skills listing', controller: 'skills' %>